name: Action Workflow

on:
  repository_dispatch:
    types: [build]
  # schedule:
  #   - cron: "1 * * * *"
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps: 
      - name: payload
        run: echo ${{github.event.client_payload.env}}
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token}}"
          # git clone git@gihub:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name : Checkout
        uses: actions/checkout@v1
      - name: List files
        run: |
          pwd
          ls -a
      - name: Simple JS actions
        id : greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Ragu
      - name: Log Greet time
        run:  echo "${{steps.greet.outputs.time}}"