name: Action Workflow

on: [push]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps: 
      - name: Simple JS actions
        id : greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Ragu
      - name: Log Greet time
        run:  echo "${{steps.greet.output.time}}"